#!/bin/bash

# This script is responsible for generating truthtables from MONA output
# It will iterate through the directory structure generated by combine-rules.sh and generate DFA TTs and NFA TTs
# IMPORTANT NOTE: This code is multi-threaded; make sure the threads variable below has a reasonable value for your computing resources


threads=10

numfiles=$2
input_dir="$1"
anml_dir="$1/tt"
ranml_dir="$1/rtt"

mkdir -p ${anml_dir}
mkdir -p ${ranml_dir}

# The task is responsible for generating truthtable files from out and rout MONA outputs
task(){
    echo "Running rules from $1 to $2"
    for i in $(eval echo {0..$numfiles});
    do
        ./MONAtoTruthTable.py ${input_dir}/ltl${i}.out ${anml_dir}/ltl${i}.tt
        ./MONAtoTruthTable.py ${input_dir}/ltl${i}.rout ${ranml_dir}/ltl${i}.tt --reverse
    done
}

max_thread_id=$((threads - 1))
# We don't have a ceiling function, so let's use this math trick
automata_per_thread=$(((num_automata + threads - 1)/threads))

last_automata=$((num_automata - 1))
for i in $(eval echo {0..$max_thread_id});
do
    start=$((i * automata_per_thread))
    end=$((start + automata_per_thread - 1))
    end=$((end>last_automata ? last_automata : end))
    task ${start} ${end} &
done

wait

